"""empty message

Revision ID: 66cf38190652
Revises: 77a1fe31aee6
Create Date: 2020-09-23 07:00:30.560988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cf38190652'
down_revision = '77a1fe31aee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_unique_constraint('unique_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email', 'users', type_='unique')
    # ### end Alembic commands ###
